# Generated by Django 5.0 on 2024-05-25 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZnHBookStore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=50)),
                ('category', models.CharField(default='', max_length=50)),
                ('subcategory', models.CharField(default='', max_length=50)),
                ('desc', models.CharField(max_length=1000)),
                ('pub_date', models.DateField()),
                ('image', models.ImageField(default='', upload_to='BookStore/images')),
                ('step1_image', models.ImageField(default='', upload_to='BookStore/step1')),
                ('step2_image', models.ImageField(default='', upload_to='BookStore/step2')),
                ('step3_image', models.ImageField(default='', upload_to='BookStore/step3')),
                ('step4_image', models.ImageField(default='', upload_to='BookStore/step4')),
                ('step5_image', models.ImageField(default='', upload_to='BookStore/step5')),
                ('step6_image', models.ImageField(default='', upload_to='BookStore/step6')),
            ],
        ),
    ]
