# Generated by Django 5.0 on 2024-06-04 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ZnHBookStore', '0009_alter_contact_user_alter_orders_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookstore',
            name='subcategory',
        ),
    ]
